version: "3.8"

services:
  db:
    restart: always
    build:
      context: ./Backend
      dockerfile: postgres/Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sbd1_database
    ports:
      - "5432:5432"
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-container
    networks:
      - postgres-network
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "80:80"

  express-api:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: express-api-container
    restart: always
    command: npm start
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/sbd1_database
    ports:
      - "3333:3333"
    networks:
      - postgres-network
    volumes:
      - ./Backend/src:/usr/src/app/src
  app-vite:
    container_name: frontend_fear_hunger
    restart: always
    stdin_open: true
    tty: true
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./FrontEnd:/usr/src/app
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: npm run dev
    depends_on:
      - express-api

networks:
  postgres-network:
    driver: bridge
