version: '3.5'
services: 
  app-vite:
    container_name: frontend_chapa_quente
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/usr/src/app
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: npm run dev
    
